### ISSUE TITLE
Nusimuša žemėlapio aprėptis perjungus naršyklės tab'us

### ISSUE THREAD

**Issue by PauliusLit** [AplinkosMinisterija/smalsuolis-web#87]
smalsuolis.lt žemėlapyje išsididinus norimą vietą ir atidarius naują tab'ą naršyklėje ir grįžus į smalsuolis.lt - žemėlapis išsididina iki LT aprėpties.

**Comment by ambrazasp** [comment]
@PauliusLit ačiū už puikų pastebėjimą! Sprendimas bus įgyvendintas jau artimiausiu metu.
